<!-- eslint-disable @typescript-eslint/no-explicit-any -->
<template>
  <v-container>
    <UiPageHeader title="Manuscript" subtitle="The canonical story for this campaign"><template #actions><v-btn data-testid="manuscript-add-scene" color="primary" @click="add('scene')">Add scene</v-btn></template></UiPageHeader>
    <v-alert v-if="!campaignId" type="info">Choose a campaign first.</v-alert>
    <v-row v-else><v-col cols="12" md="4"><v-btn-group class="mb-3"><v-btn v-for="type in ['book', 'part', 'chapter']" :key="type" :data-testid="`manuscript-add-${type}`" @click="add(type)">Add {{ type }}</v-btn></v-btn-group><v-list lines="two"><v-list-item v-for="section in sections" :key="section.id" :data-testid="`manuscript-section-${section.title}`" :active="selected?.id === section.id" :title="section.title" :subtitle="section.section_type" @click="select(section)"><template #prepend><v-icon :icon="icons[section.section_type]" /></template><template #append><v-btn data-testid="manuscript-move-up" aria-label="Move section up" icon="mdi-arrow-up" size="x-small" variant="text" @click.stop="move(section, -1)" /><v-btn data-testid="manuscript-move-down" aria-label="Move section down" icon="mdi-arrow-down" size="x-small" variant="text" @click.stop="move(section, 1)" /></template></v-list-item></v-list></v-col><v-col cols="12" md="8"><v-card v-if="selected"><v-card-title class="d-flex ga-2"><v-text-field v-model="selected.title" data-testid="manuscript-title" hide-details @blur="save" /><v-btn data-testid="manuscript-delete" aria-label="Delete section" icon="mdi-delete" variant="text" @click="remove" /></v-card-title><v-card-text><v-row><v-col cols="12" sm="4"><v-select v-model="selected.section_type" label="Level" :items="['book', 'part', 'chapter', 'scene']" @update:model-value="save" /></v-col><v-col cols="12" sm="4"><v-text-field v-model="selected.viewpoint" label="Viewpoint" @blur="save" /></v-col><v-col cols="12" sm="4"><v-text-field v-model="selected.story_date" label="Story date" type="date" @blur="save" /></v-col></v-row><SharedEntityMarkdownEditor v-model="selected.content" @update:model-value="save" /><v-expansion-panels class="mt-3"><v-expansion-panel title="Revisions"><v-expansion-panel-text><v-list density="compact"><v-list-item v-for="revision in revisions" :key="revision.id" :title="revision.created_at"><template #append><v-btn data-testid="manuscript-restore-revision" size="small" @click="restore(revision.id)">Restore</v-btn></template></v-list-item></v-list></v-expansion-panel-text></v-expansion-panel></v-expansion-panels></v-card-text></v-card><v-empty-state v-else title="Start your story" text="Add a scene, chapter, part, or book to begin." /></v-col></v-row>
  </v-container>
</template>

<script setup lang="ts">
/* eslint-disable @typescript-eslint/no-explicit-any */
const campaign = useCampaignStore()
const campaignId = computed(() => campaign.activeCampaignIdNumber)
const icons: Record<string, string> = { book: 'mdi-book-open-page-variant', part: 'mdi-bookmark', chapter: 'mdi-format-list-numbered', scene: 'mdi-script-text' }
const { data, refresh } = await useAsyncData(() => campaignId.value ? $fetch<{ sections: any[] }>(`/api/campaigns/${campaignId.value}/manuscript`) : Promise.resolve(null), { watch: [campaignId] })
const sections = computed(() => data.value?.sections || [])
const selected = ref<any>(null)
const { data: revisions, refresh: refreshRevisions } = await useAsyncData(() => campaignId.value && selected.value ? $fetch<any[]>(`/api/campaigns/${campaignId.value}/manuscript/sections/${selected.value.id}/revisions`) : Promise.resolve([]), { watch: [campaignId, selected] })
function select(section: any) { selected.value = { ...section } }
async function add(section_type: string) { if (!campaignId.value) return; const title = prompt(`New ${section_type} title`, `New ${section_type}`); if (!title) return; const created = await $fetch<any>(`/api/campaigns/${campaignId.value}/manuscript/sections`, { method: 'POST', body: { title, section_type, parent_section_id: section_type === 'scene' ? selected.value?.id : null } }); await refresh(); select(created) }
async function save() { if (!campaignId.value || !selected.value) return; await $fetch(`/api/campaigns/${campaignId.value}/manuscript/sections/${selected.value.id}`, { method: 'PATCH', body: selected.value }); await refresh(); await refreshRevisions() }
async function move(section: any, delta: number) { const ids = sections.value.map((item: any) => item.id); const index = ids.indexOf(section.id); const target = index + delta; if (target < 0 || target >= ids.length || !campaignId.value) return; [ids[index], ids[target]] = [ids[target], ids[index]]; await $fetch(`/api/campaigns/${campaignId.value}/manuscript/sections/reorder`, { method: 'PATCH', body: { ids } }); await refresh() }
async function remove() { if (!campaignId.value || !selected.value || !confirm(`Delete ${selected.value.title}?`)) return; await $fetch(`/api/campaigns/${campaignId.value}/manuscript/sections/${selected.value.id}`, { method: 'DELETE' }); selected.value = null; await refresh() }
async function restore(id: number) { if (!campaignId.value || !selected.value) return; selected.value = await $fetch(`/api/campaigns/${campaignId.value}/manuscript/sections/${selected.value.id}/revisions/${id}/restore`, { method: 'POST' }); await refresh(); await refreshRevisions() }
</script>
